apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cockroachdb
  namespace: hat-shop
spec:
  template:
    spec:
      subdomain: crdb-b
      containers:
        - name: cockroachdb
          command:
            - /cockroach/cockroach
            - start
            - --insecure
            - --advertise-host=$(POD_NAME).crdb-b.hat-shop.svc.cluster.local
            - --http-addr=0.0.0.0:8080
            - --listen-addr=0.0.0.0:26257
            - --cache=256MiB
            - --max-sql-memory=256MiB
            - --cluster-name=hat-shop
            - --join=cockroachdb-0.crdb-b.hat-shop.svc.cluster.local:26257,cockroachdb-1.crdb-b.hat-shop.svc.cluster.local:26257,cockroachdb-0.crdb-a.hat-shop.svc.clusterset.local:26257,cockroachdb-1.crdb-a.hat-shop.svc.clusterset.local:26257
