apiVersion: v1
kind: Service
metadata:
  name: front-end
  namespace: hat-shop
  labels:
    app: front-end
spec:
  type: NodePort
  selector:
    app: front-end
  ports:
    - port: 3000
      targetPort: 3000
      name: http
      nodePort: 30000
