apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-config
  namespace: hat-shop
data:
  CLUSTER_NAME: "cluster-a"
  crdb_subdomain: "crdb-a"
  kafka_subdomain: "kafka-a"
  DATABASE_URL: "postgresql://root@cockroachdb-public.hat-shop.svc.cluster.local:26257/defaultdb?sslmode=disable"
  KAFKA_ADDR: "kafka-bootstrap.hat-shop.svc.cluster.local:9092"
  # Point to your external OTEL collector (docker-compose host).
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://OTEL_COLLECTOR_HOST:4318"
