apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ../../infra

patches:
  - path: cluster-config-patch.yaml
  - path: crdb-args-patch.yaml
  - path: kafka-env-patch.yaml
